# name 可以自定义
name: CI
# 指定触发workflow的条件
# 下面的意思就是在监听到main分支push操作的时候运行
on:
  schedule:
  
    - cron: '* * * * *'

# jobs 表示要执行的一项或者多项任务
jobs:
  # 任务名，可自定义
  autoPush:
    # runs-on字段指定运行所需要的虚拟机环境。它是必填字段。目前可用的虚拟机如下。
    runs-on: ubuntu-latest
    # steps表示执行步骤
    steps:
    # 检出代码，这里用了 actions/checkout@master 库来完成
    - name: Checkout
      uses: actions/checkout@v2
   # 这里展示了如何执行多条命令
    - name: Run and Push
      run: |
        npm start
        git add .
        git commit -m "commit"
        git push
